spring:
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://47.96.31.212:3306/yaiun_db?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: yaiun_root
    password: YaiunRoot123456.
  redis:
    host: 47.96.31.212
    password:
    port: 6379
    database: 2